appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: ZTUfQur9fCpDmhyOedKNF/FZXYUBrNRIyAX+v+23GMlxR0eA+JeHBTw/a53P6mL2vs4JQ/wlRecUJmdqTMlcL/n/vYEPJYcbHc2t1aoxqe8mYupprnnSae3tQZhzKHXk85p3uIgHEHR7yEZC7sdeWR2spNrVD7DV2vMbZkAvDdYtwU0H74yW6lwRKuwYJ5eENHcQQ9NAMWD++kKoxBH2ary9DK10F2EyHfcahDCNjD0qZy1OEfV7BO/Rs6EraXW+znX/Kvt1musznBzNR6KF1gg2pW1Rcot5rsFtnal6GeM8Gu0TSysufyzL5GdbMI7Ul0nWn4DZBufDYn9dxPeHMFqSrur7dG+2z1KmHGAVGPll7f+sp5NqpVWFFXoTbhn24XtPKCMnBpQoOMGGcLwEqzx3LfAdm6+FaFQY6WIF5XGh8fc7CLu88G12/K+5LhNVwiVy5Bx/aTPo5ROqtU0seb78Lcf0KiuzCYDJYmrrMuNTXWwnFu9nBY3JvRIP3uFoo6fWwVzZppf1Tmp2egVYsq59FgLcyQ5mn35FWEcIWte3r2v2AvtahA6+Nhy3RvESyfAy+A59UTw1QY+99qLLs6FejDtIYEWnVTF/Yx95JN/FBg4K8l0DPqz48LmC2W+WoaHUN2Tbrg7sSKOaHkoZm8c6SKfq5JosCjOCFbi0Vl0=
conda_forge_output_validation: true
