travis:
  secure:
    BINSTAR_TOKEN: pG+Q4eaaUE+zA/jZRlmeiFg1LY/lkZOmQLuKgAoikIf6CS6sSnP/dHwilZ9awp5k+O2xkMEIK4rv6MpU8bRKa4aTgjn83V0G2CyvqDTWRZ4A7w6jGcfbQjWuXosMRyFC0xMLLnex4jieYh1Zh1EuPIcVU4YKYUtXIa8gCh7RLReV8E8j0+CrJj2kSU0yMjsJzDy8W8fhdKKd9vEpnSTxH4iHB1Qw5ZSZN5sNKf+Nne5VTUZX53GPZ2N5zxUTli+7diOvZt8T7YybZibeE2L4389VzR0rxu/7yPUmcrY+XGw72XTsK0CQbtTI5qEtN5lIN8DPEANWBD5rFspRLWOtSBIzcJasPxk/gCPX4VUAM0QgoZSTBcwHhXrVBqF0JCXq0bf9J8zJ4SGGt0+shWXF8+Ljbhq8DynUTMpGVmy1oRZD2izy/+lGHCIPr1jIjdAjhzqNYlHG7Mebuqn0y2l3EZHdc9d7l6ZAaUogL6RD6dlnsu3clmHmLuIREm7Kvct/tSR04XEk3hS04jhRDXeAhSn9DMaiGql0+rVFtwSxxZ9f3TLmqHK9Pyg+IqDuLJdNlvWvTvDRaxwReRCPf11FC7i1mN1ego+huhMCefFm2QEVrFJZcbhEc35e0nXIldvq15te90f8N7nZsZ1a27JV90psUpB4NmYVsMtijtJM1RM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
