travis:
  secure:
    BINSTAR_TOKEN: X2tNW5bt+C9Bg9e/58drV+XO9GeXh7TIhDCD/OF/m5N3r2qw8DwuWHvuSk4MWg0ziuFriEH1G7NFXaf3xPVy2XPKso5AqHf5NVb81H9wvIQiFwXLypsvyyHATX7JZHoRebcQFUsLJ6zIkxP4gFknGmbBqrPw5uQ6ib38a+8qbFtSF4QFAa3MRkREsBVyDMyQljeojPMKnHwdB7h8rkG1ysPtpYhGDGh4wDS2WGMYC62Gyh+LaceQNsVQ/gkXynD68DRkq06mK8pooZ5Eq7heWp44f1YzoGc4pW36vFKleNLqE9aXNnsElI5HidNX2LGk/mjScPbyB7zfAeFVxk9RF6CdGyaG88M4brN0WynW8QxdeQdiYY1Rm8cCRZ27JAY+STjSC0q3EUm33mRRjp8MD1BWh+KEAPRODvykscBpLZJDcHtvHSUjEHVs1wWMj+GINmTk7kUAjMkssqKuqhYhqwrWpWCEjQFg62Sm/DcfNXAP7wnjxVo7Yaa9t3DGueWDq4mGz83BfCbgadJxaFyKhj7xtFKCq2aIv80vNWNBQedzmUwfz0NeR40ZsAoxAIrUeGj7ALAwsUGyJXaVU8TyO3n8YJUg/IJHhPXYmoe+EzlfhmhY94BWHbIwkg7vMzLOIfjZJbYdQtureagTxMq10WRCfGShtIQjG4a6B9DelhA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
